services:
  - type: web
    name: medcopilot-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/nltk_data
      NLTK_DATA=/opt/render/project/src/nltk_data python /opt/render/project/src/backend/download_nltk.py
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: OPENAI_API_KEY
        sync: false 